routes/web.php
<?php

use App\Http\Controllers\PostsController;
use App\Http\Controllers\UsersController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', [\App\Http\Controllers\FrontendController::class, 'index'])->name('home');
Route::get('/blogs/category/{category}', [\App\Http\Controllers\FrontendController::class, 'categories'])->name('category.blogs');
Route::get('/blogs/tag/{tag}', [\App\Http\Controllers\FrontendController::class, 'tags'])->name('tag.blogs');

/**
 * ADMIN PANEL
 */

Route::middleware(['auth'])->group(function() {
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    });
    Route::resource('posts', \App\Http\Controllers\PostsController::class);

    Route::get('/trashed/posts', [\App\Http\Controllers\PostsController::class,'trashed'])->name('posts.trashed');
    Route::put('/restored/posts/{post}', [\App\Http\Controllers\PostsController::class,'restored'])->withTrashed()->name('posts.restored');
    Route::delete('/trashDelete/posts/{post}', [\App\Http\Controllers\PostsController::class,'trashDeleted'])->withTrashed()->name('posts.trashDeleted');

    Route::get('/singlePost/{post}', [\App\Http\Controllers\PostsController::class, 'singlePost'])->name('posts.singlePost');
    Route::get('/singlePost/category/{category}', [\App\Http\Controllers\PostsController::class, 'categories'])->name('category.singlePost');
    Route::get('/singlePost/tag/{tag}', [\App\Http\Controllers\PostsController::class, 'tags'])->name('tag.singlePost');

    Route::resource('categories', \App\Http\Controllers\CategoriesController::class);
    Route::resource('tags', \App\Http\Controllers\TagsController::class)->except('show');
});

Route::middleware(['auth', 'admin'])->group(function() {
    Route::get('/users', [UsersController::class, 'index'])->name('users.index');
    Route::put('/users/{user}/make-admin', [UsersController::class, 'makeAdmin'])->name('users.makeAdmin');
    Route::put('/users/{user}/make-author', [UsersController::class, 'makeAuthor'])->name('users.makeAuthor');
});

require __DIR__.'/auth.php';

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;
    protected $fillable = ['name'];

    /**
     * @return int
     * Accessor to return post count related to category
     */
    public function getPostsCountAttribute()
    {
        return $this->posts()->count();
    }
    
    /** RELATIONSHIP METHODS */
    public function posts() {
        return $this->hasMany(Post::class);
    }
}

resources/views/frontend/singlepost/layout/partials/_footer.blade.php
<!-- Footer Area
=====================================-->
<footer id="footer" class="footer-one center-block bg-light pt50 pb30 ">
    <div class="container">
        <div class="row">

            <div class="col-md-2 col-xs-12 mb25">
                <div class="navbar-brand-footer center-block">Pen-It</div>
                <div class="copyright center-block">&copy; 2020. All rights reserved.</div>
            </div>

            <div class="col-md-8 col-xs-12 text-center">
                <div class="row">
                    <div class="col-sm-12">
                        <ul class=" bb-solid-1">
                            <li><a href="#">Home</a></li>
                            <li><a href="#">Post</a></li>
                        </ul>
                    </div>

                    <div class="col-sm-12 mt25">
                        <ul>
                            <li><a href="#">Help Center</a></li>
                            <li><a href="#">Knowledgebase</a></li>
                            <li><a href="#">Term of Service</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">FAQs</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="col-md-2 col-xs-12">
                <div class="social-container">
                    <ul class="footer-social text-center">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-github"></i></a></li>
                        <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                    </ul>
                </div>
            </div>

        </div>
    </div>
</footer>

resources/views/frontend/singlepost/layout/partials/_header.blade.php
<header class="pt100 pb100 parallax-window-2" data-parallax="scroll" data-speed="0.5" data-image-src="{{ asset('frontend/assets/img/bg/img-bg-17.jpg') }}" data-positiony="1000">
    <div class="intro-body text-center">
        <div class="container">
            <div class="row">
                <div class="col-md-12 pt50">
                    <h1 class="brand-heading font-montserrat text-uppercase color-light" data-in-effect="fadeInDown">
                        Blog Post
                        <small class="color-light alpha7">Articulated for You with &hearts;</small>
                    </h1>
                </div>
            </div>
        </div>

    </div>
</header>

resources/views/frontend/singlepost/layout/partials/_navbar.blade.php
<!-- Navigation Area
===================================== -->
<nav class="navbar navbar-pasific navbar-mp megamenu navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand page-scroll" href="#page-top">
                <img src="{{ asset('frontend/assets/img/logo/logo-default.png') }}" alt="logo">
                Pen-It
            </a>
        </div>

        <div class="navbar-collapse collapse navbar-main-collapse">
            <ul class="nav navbar-nav">
                <li>
                    <a href="index.html" data-toggle="dropdown" class="dropdown-toggle color-light">Home </a>
                </li>
            </ul>

        </div>
    </div>
</nav>

resources/views/frontend/singlepost/layout/partials/_newsletter.blade.php
<!-- Newsletter Area
=====================================-->
<section id="newsletter" class="bg-dark2 pt50 pb50">
    <div class="container">
        <div class="row">

            <div class="col-md-2">
                <h4 class="color-light">
                    Newsletter
                </h4>
            </div>

            <div class="col-md-10">
                <form name="newsletter">
                    <div class="input-newsletter-container">
                        <input type="text" name="email" class="input-newsletter" placeholder="enter your email address">
                    </div>
                    <a href="#" class="button button-sm button-pasific hover-ripple-out">Subscribe<i class="fa fa-envelope"></i></a>
                </form>
            </div>
        </div>
    </div>
</section>

resources/views/frontend/singlepost/layout/partials/_sidebar.blade.php
<!-- Search===================================== -->
<div class="pr25 pl25 clearfix">
    <form action="#">
        <div class="blog-sidebar-form-search">
            <input type="text" name="search" class="" placeholder="e.g. Javascript">
            <button type="submit" name="submit" class="pull-right"><i class="fa fa-search"></i></button>
        </div>
    </form>

</div>

<!-- Categories===================================== -->
<div class="mt25 pr25 pl25 clearfix">
    <h5 class="mt25">
        Categories
        <span class="heading-divider mt10"></span>
    </h5>
    <ul class="blog-sidebar pl25">
        @foreach ($categories as $category)
            <li class="active"><a href="{{ route('category.singlePost', $category->id) }}">{{ $category->name }}<span class="badge badge-pasific pull-right">{{ $category->posts_count }}</span></a>
            </li>
        @endforeach
    </ul>

</div>

<!-- Tags===================================== -->
<div class="pr25 pl25 clearfix">
    <h5 class="mt25">
        Popular Tags
        <span class="heading-divider mt10"></span>
    </h5>
    <ul class="tag">
        @foreach ($tags as $tag)
            <li><a href="{{ route('tag.singlePost', $tag->id) }}">{{ $tag->name }}</a></li>
        @endforeach
    </ul>

</div>